### ISSUE TITLE
Book Show: Reader can remove a book from their library

### ISSUE THREAD

**Issue by aliyamerali** [Caleb1991/epeolatry_front_end#12]
If a book is in the reader’s library, the reader will see a button to “Remove from Library.” Clicking this button will remove the book from the reader’s library in the Google Books DB.

- Removing a book from the reader’s library should destroy words added for that book
- Upon deleting the book, the user is redirected to the books index page, where they no longer see this book listed

FE will ping: 
DELETE (remove a book from library) / epeolatry API 

BE will need: 
DELETE (remove a book from library) / Google Books API

**Comment by LawrenceWhalen** [comment]
Ready to controller level, will need to use a redirect in the controller based off the page we call this from.
