### ISSUE TITLE
Books Index: Shows all of the logged in reader’s books

### ISSUE THREAD

**Issue by aliyamerali** [Caleb1991/epeolatry_front_end#7]
- Book’s Attributes: Title, author, shelf
- Title links to book show page
- Should be paginated

FE will ping: GET (reader’s books) / epeolatry API
BE will need to ping: GET (reader’s books) / Google Books API

**Comment by LawrenceWhalen** [comment]
This is ready to the controller level, we moved paginating this to extensions. No link to show page until single book endpoint from BE.
