### ISSUE TITLE
Books Index: Reader sees a search bar to search for a new book

### ISSUE THREAD

**Issue by aliyamerali** [Caleb1991/epeolatry_front_end#9]
- Search output is shown in a “Search Results” section (separate from the book index)
- Search result title links to book show page
- Search results should be paginated

FE will ping: GET (book search results) / epeolatry API
BE will need: GET (book search results) / Google Books API

**Comment by LawrenceWhalen** [comment]
The call to backend is set-up here. We can send a search and page to return as many books as we need using a next page button. Waiting on a single book call from BE for show page. No actual view implemented. ready at controller level.
